from __future__ import annotations

from app.engines.schemas import EngineDefinition, EngineKind


ENGINE_DEFINITIONS: tuple[EngineDefinition, ...] = (
    EngineDefinition(
        engine_id="edge",
        display_name="Edge TTS",
        kind=EngineKind.INTERNET,
        built_in=True,
        import_checks=("edge_tts",),
        default_config={
            "voice": "pl-PL-MarekNeural",
            "rate": "+0%",
            "pitch": "+0Hz",
            "audio_qc_enabled": False,
            "audio_qc_retry_attempts": 2,
            "edge_apply_segment_fade": True,
            "edge_trim_start_ms": 180,
            "edge_trim_end_ms": 800,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
    EngineDefinition(
        engine_id="openai",
        display_name="OpenAI TTS",
        kind=EngineKind.INTERNET,
        built_in=True,
        import_checks=("openai",),
        requires_api_key=True,
        default_config={
            "api_key": "",
            "model": "gpt-4o-mini-tts",
            "voice": "marin",
            "instructions": "Mow po polsku spokojnym, neutralnym glosem lektora. Zachowaj czytelna dykcje i naturalne tempo.",
            "audio_qc_enabled": False,
            "audio_qc_retry_attempts": 2,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": False,
            "whisper_qc_retry_attempts": 1,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.62,
        },
    ),
    EngineDefinition(
        engine_id="chatterbox",
        display_name="Chatterbox",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("chatterbox", "soundfile"),
        default_config={
            "t3_model": "v2",
            "audio_prompt_path": "",
            "trim_leading_silence": True,
            "cfg_weight": 1.9,
            "exaggeration": 0.1,
            "device": "auto",
            "seed": 12345,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
    EngineDefinition(
        engine_id="omnivoice",
        display_name="OmniVoice",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("omnivoice", "soundfile"),
        default_config={
            "device": "auto",
            "reference_audio_path": "",
            "reference_text": "",
            "num_step": 48,
            "guidance_scale": 3.8,
            "speed": 1.0,
            "denoise": True,
            "preprocess_prompt": False,
            "postprocess_output": False,
            "omnivoice_trim_edges": True,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
    EngineDefinition(
        engine_id="piper",
        display_name="Piper TTS",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("piper", "soundfile"),
        default_config={
            "voice": "pl_PL-mc_speech-medium",
            "length_scale": 1.1,
            "noise_scale": 0.05,
            "noise_w_scale": 0.05,
            "speaker_id": 0,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 5,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.93,
        },
    ),
    EngineDefinition(
        engine_id="coqui_xtts",
        display_name="Coqui XTTS-v2",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("TTS", "soundfile"),
        default_config={
            "device": "auto",
            "speaker_wav_path": "",
            "speaker": "Anna",
            "temperature": 0.1,
            "length_penalty": 1.0,
            "repetition_penalty": 9.0,
            "top_k": 100,
            "top_p": 1.0,
            "builtin_voice_speed": 1.6,
            "voice_sample_speed": 1.3,
            "xtts_trim_trailing_silence": True,
            "save_processed_subtitles": False,
            "save_quality_report": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 4,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.93,
        },
    ),
)


def get_engine_definitions() -> tuple[EngineDefinition, ...]:
    return ENGINE_DEFINITIONS
