from __future__ import annotations

from app.engines.schemas import EngineDefinition, EngineKind


ENGINE_DEFINITIONS: tuple[EngineDefinition, ...] = (
    EngineDefinition(
        engine_id="edge",
        display_name="Edge TTS",
        kind=EngineKind.INTERNET,
        built_in=True,
        import_checks=("edge_tts",),
        default_config={
            "voice": "pl-PL-MarekNeural",
            "rate": "+0%",
            "pitch": "+0Hz",
            "audio_qc_enabled": False,
            "audio_qc_retry_attempts": 2,
            "edge_apply_segment_fade": True,
            "edge_trim_start_ms": 180,
            "edge_trim_end_ms": 800,
            "save_processed_subtitles": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
    EngineDefinition(
        engine_id="openai",
        display_name="OpenAI TTS",
        kind=EngineKind.INTERNET,
        built_in=True,
        import_checks=("openai",),
        requires_api_key=True,
        default_config={
            "api_key": "",
            "model": "gpt-4o-mini-tts",
            "voice": "marin",
            "instructions": "Mow po polsku spokojnym, neutralnym glosem lektora. Zachowaj czytelna dykcje i naturalne tempo.",
            "audio_qc_enabled": False,
            "audio_qc_retry_attempts": 2,
            "save_processed_subtitles": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": False,
            "whisper_qc_retry_attempts": 1,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.62,
        },
    ),
    EngineDefinition(
        engine_id="chatterbox",
        display_name="Chatterbox",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("chatterbox", "faster_whisper", "soundfile"),
        default_config={
            "t3_model": "v2",
            "audio_prompt_path": "",
            "trim_leading_silence": True,
            "cfg_weight": 1.9,
            "exaggeration": 0.1,
            "device": "auto",
            "seed": 12345,
            "save_processed_subtitles": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
    EngineDefinition(
        engine_id="omnivoice",
        display_name="OmniVoice",
        kind=EngineKind.LOCAL,
        requires_venv=True,
        requires_model=True,
        import_checks=("omnivoice", "soundfile"),
        default_config={
            "device": "auto",
            "reference_audio_path": "",
            "reference_text": "",
            "num_step": 48,
            "guidance_scale": 3.8,
            "speed": 1.0,
            "denoise": True,
            "preprocess_prompt": False,
            "postprocess_output": False,
            "omnivoice_trim_edges": True,
            "save_processed_subtitles": False,
            "save_run_reports": False,
            "save_lektor_segments": False,
            "save_lektor_track_before_normalization": False,
            "save_lektor_track_after_normalization": False,
            "save_audio_mix_steps": False,
            "whisper_qc_enabled": True,
            "whisper_qc_retry_attempts": 3,
            "whisper_qc_model": "small",
            "whisper_qc_min_similarity": 0.92,
        },
    ),
)


def get_engine_definitions() -> tuple[EngineDefinition, ...]:
    return ENGINE_DEFINITIONS
