from __future__ import annotations


STT_LANGUAGE_OPTIONS: tuple[tuple[str, str], ...] = (
    ("auto", "Auto - wykryj automatycznie"),
    ("af", "af - Afrikaans"),
    ("am", "am - Amharski"),
    ("ar", "ar - Arabski"),
    ("as", "as - Asamski"),
    ("az", "az - Azerbejdzanski"),
    ("ba", "ba - Baszkirski"),
    ("be", "be - Bialoruski"),
    ("bg", "bg - Bulgarski"),
    ("bn", "bn - Bengalski"),
    ("bo", "bo - Tybetanski"),
    ("br", "br - Bretonski"),
    ("bs", "bs - Bosniacki"),
    ("ca", "ca - Katalonski"),
    ("cs", "cs - Czeski"),
    ("cy", "cy - Walijski"),
    ("da", "da - Dunski"),
    ("de", "de - Niemiecki"),
    ("el", "el - Grecki"),
    ("en", "en - Angielski"),
    ("es", "es - Hiszpanski"),
    ("et", "et - Estonski"),
    ("eu", "eu - Baskijski"),
    ("fa", "fa - Perski"),
    ("fi", "fi - Finski"),
    ("fo", "fo - Farerski"),
    ("fr", "fr - Francuski"),
    ("gl", "gl - Galicyjski"),
    ("gu", "gu - Gudzerati"),
    ("ha", "ha - Hausa"),
    ("haw", "haw - Hawajski"),
    ("he", "he - Hebrajski"),
    ("hi", "hi - Hindi"),
    ("hr", "hr - Chorwacki"),
    ("ht", "ht - Haitanski kreolski"),
    ("hu", "hu - Wegierski"),
    ("hy", "hy - Ormianski"),
    ("id", "id - Indonezyjski"),
    ("is", "is - Islandzki"),
    ("it", "it - Wloski"),
    ("ja", "ja - Japonski"),
    ("jw", "jw - Jawajski"),
    ("ka", "ka - Gruzinski"),
    ("kk", "kk - Kazachski"),
    ("km", "km - Khmerski"),
    ("kn", "kn - Kannada"),
    ("ko", "ko - Koreanski"),
    ("la", "la - Lacina"),
    ("lb", "lb - Luksemburski"),
    ("ln", "ln - Lingala"),
    ("lo", "lo - Laotanski"),
    ("lt", "lt - Litewski"),
    ("lv", "lv - Lotewski"),
    ("mg", "mg - Malgaski"),
    ("mi", "mi - Maoryski"),
    ("mk", "mk - Macedonski"),
    ("ml", "ml - Malajalam"),
    ("mn", "mn - Mongolski"),
    ("mr", "mr - Marathi"),
    ("ms", "ms - Malajski"),
    ("mt", "mt - Maltanski"),
    ("my", "my - Birmanski"),
    ("ne", "ne - Nepalski"),
    ("nl", "nl - Niderlandzki"),
    ("nn", "nn - Norweski nynorsk"),
    ("no", "no - Norweski"),
    ("oc", "oc - Oksytanski"),
    ("pa", "pa - Pendzabski"),
    ("pl", "pl - Polski"),
    ("ps", "ps - Paszto"),
    ("pt", "pt - Portugalski"),
    ("ro", "ro - Rumunski"),
    ("ru", "ru - Rosyjski"),
    ("sa", "sa - Sanskryt"),
    ("sd", "sd - Sindhi"),
    ("si", "si - Syngaleski"),
    ("sk", "sk - Slowacki"),
    ("sl", "sl - Slowenski"),
    ("sn", "sn - Shona"),
    ("so", "so - Somalijski"),
    ("sq", "sq - Albanski"),
    ("sr", "sr - Serbski"),
    ("su", "su - Sundajski"),
    ("sv", "sv - Szwedzki"),
    ("sw", "sw - Suahili"),
    ("ta", "ta - Tamilski"),
    ("te", "te - Telugu"),
    ("tg", "tg - Tadzycki"),
    ("th", "th - Tajski"),
    ("tk", "tk - Turkmenski"),
    ("tl", "tl - Tagalog"),
    ("tr", "tr - Turecki"),
    ("tt", "tt - Tatarski"),
    ("uk", "uk - Ukrainski"),
    ("ur", "ur - Urdu"),
    ("uz", "uz - Uzbecki"),
    ("vi", "vi - Wietnamski"),
    ("yi", "yi - Jidysz"),
    ("yo", "yo - Joruba"),
    ("zh", "zh - Chinski"),
)

STT_LANGUAGE_CODES: tuple[str, ...] = tuple(code for code, _label in STT_LANGUAGE_OPTIONS)
STT_LANGUAGE_LABELS: tuple[str, ...] = tuple(label for _code, label in STT_LANGUAGE_OPTIONS)
STT_LANGUAGE_LABEL_BY_CODE: dict[str, str] = dict(STT_LANGUAGE_OPTIONS)


def stt_language_label(code: str) -> str:
    normalized = str(code or "").strip().lower()
    return STT_LANGUAGE_LABEL_BY_CODE.get(normalized, normalized or "auto")
